//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by slg2.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SLG2TYPE                    129
#define IDS_SOFTWARE_VERSION            129
#define IDD_MAIN_WINDOW                 130
#define IDD_WIZARD_STEP_COM             132
#define IDD_WIZARD_MEAS_TYPE_SEL        134
#define IDD_DLG_HISTO                   135
#define IDD_DLG_ALAN_CURVE              137
#define IDD_DLG_EXPORT                  139
#define IDD_OPEN_MEAS_DLG               140
#define IDI_RED                         141
#define IDI_BLUE                        142
#define IDC_GRAPH1                      1000
#define IDC_GRAPH2                      1001
#define IDC_CMB_COM                     1001
#define IDC_GRAPH3                      1002
#define IDC_CMB_BAUDRATE                1002
#define IDC_GRAPH4                      1003
#define IDC_GRAPH5                      1004
#define IDC_GRAPH6                      1005
#define IDC_GRAPH7                      1006
#define IDC_GRAPH8                      1007
#define IDC_MAIN_GRAPH                  1008
#define IDC_INDICATOR_COM               1009
#define IDC_ST_1                        1010
#define IDC_ST_2                        1011
#define IDC_ST_3                        1012
#define IDC_ST_4                        1013
#define IDC_ST_5                        1014
#define IDC_ST_6                        1015
#define IDC_BTN_START                   1016
#define IDC_ST_7                        1017
#define IDC_TEST_RAD                    1017
#define IDC_EXEC_RAD                    1018
#define IDC_SEL_ANG_RATE_UNITS          1018
#define IDC_CW_START                    1019
#define IDC_CMB_COM_PORT                1020
#define IDC_STATISTIC_FRAME             1022
#define IDC_MIN_LABEL                   1023
#define IDC_MEAN_LABEL                  1024
#define IDC_MAX_LABEL                   1025
#define IDC_RMS_LABEL                   1026
#define IDC_MINVAL_LABEL                1027
#define IDC_MEANVAL_LABEL               1028
#define IDC_MAXVAL_LABEL                1029
#define IDC_RMSVAL_LABEL                1030
#define IDC_GRAPH1_MIN_LABEL            1031
#define IDC_GRAPH1_MINVAL_LABEL         1032
#define IDC_GRAPH1_MEAN_LABEL           1033
#define IDC_GRAPH1_MEANVAL_LABEL        1034
#define IDC_GRAPH1_MAX_LABEL            1035
#define IDC_GRAPH1_MAXVAL_LABEL         1036
#define IDC_GRAPH1_RMS_LABEL            1037
#define IDC_GRAPH1_RMSVAL_LABEL         1038
#define IDC_GRAPH2_MIN_LABEL            1039
#define IDC_GRAPH2_MINVAL_LABEL         1040
#define IDC_GRAPH2_MEAN_LABEL           1041
#define IDC_GRAPH2_MEANVAL_LABEL        1042
#define IDC_GRAPH2_MAX_LABEL            1043
#define IDC_GRAPH2_MAXVAL_LABEL         1044
#define IDC_GRAPH2_RMS_LABEL            1045
#define IDC_GRAPH2_RMSVAL_LABEL         1046
#define IDC_GRAPH3_MIN_LABEL            1047
#define IDC_GRAPH3_MINVAL_LABEL         1048
#define IDC_GRAPH3_MEAN_LABEL           1049
#define IDC_GRAPH3_MEANVAL_LABEL        1050
#define IDC_GRAPH3_MAX_LABEL            1051
#define IDC_GRAPH3_MAXVAL_LABEL         1052
#define IDC_GRAPH3_RMS_LABEL            1053
#define IDC_GRAPH3_RMSVAL_LABEL         1054
#define IDC_GRAPH4_MIN_LABEL            1055
#define IDC_GRAPH4_MINVAL_LABEL         1056
#define IDC_GRAPH4_MEAN_LABEL           1057
#define IDC_GRAPH4_MEANVAL_LABEL        1058
#define IDC_GRAPH4_MAX_LABEL            1059
#define IDC_GRAPH4_MAXVAL_LABEL         1060
#define IDC_GRAPH4_RMS_LABEL            1061
#define IDC_GRAPH4_RMSVAL_LABEL         1062
#define IDC_GRAPH5_MIN_LABEL            1063
#define IDC_GRAPH5_MINVAL_LABEL         1064
#define IDC_GRAPH5_MEAN_LABEL           1065
#define IDC_GRAPH5_MEANVAL_LABEL        1066
#define IDC_GRAPH5_MAX_LABEL            1067
#define IDC_GRAPH5_MAXVAL_LABEL         1068
#define IDC_GRAPH5_RMS_LABEL            1069
#define IDC_GRAPH5_RMSVAL_LABEL         1070
#define IDC_GRAPH6_MIN_LABEL            1071
#define IDC_GRAPH6_MINVAL_LABEL         1072
#define IDC_GRAPH6_MEAN_LABEL           1073
#define IDC_GRAPH6_MEANVAL_LABEL        1074
#define IDC_GRAPH6_MAX_LABEL            1075
#define IDC_GRAPH6_MAXVAL_LABEL         1076
#define IDC_GRAPH6_RMS_LABEL            1077
#define IDC_GRAPH6_RMSVAL_LABEL         1078
#define IDC_GRAPH7_MIN_LABEL            1079
#define IDC_GRAPH7_MINVAL_LABEL         1080
#define IDC_GRAPH7_MEAN_LABEL           1081
#define IDC_GRAPH7_MEANVAL_LABEL        1082
#define IDC_GRAPH7_MAX_LABEL            1083
#define IDC_GRAPH7_MAXVAL_LABEL         1084
#define IDC_GRAPH7_RMS_LABEL            1085
#define IDC_GRAPH7_RMSVAL_LABEL         1086
#define IDC_GRAPH8_MIN_LABEL            1087
#define IDC_GRAPH8_MINVAL_LABEL         1088
#define IDC_GRAPH8_MEAN_LABEL           1089
#define IDC_GRAPH8_MEANVAL_LABEL        1090
#define IDC_GRAPH8_MAX_LABEL            1091
#define IDC_GRAPH8_MAXVAL_LABEL         1092
#define IDC_GRAPH8_RMS_LABEL            1093
#define IDC_GRAPH8_RMSVAL_LABEL         1094
#define IDC_EMERGENCY_LBL               1098
#define IDC_PARAM1_BTN                  1100
#define IDC_PARAM1_VAL                  1101
#define IDC_PARAM5_BTN                  1102
#define IDC_PARAM2_BTN                  1103
#define IDC_PARAM2_VAL                  1104
#define IDC_PARAM5_VAL                  1105
#define IDC_PARAM3_BTN                  1106
#define IDC_PARAM3_VAL                  1107
#define IDC_PARAM6_BTN                  1108
#define IDC_PARAM4_BTN                  1109
#define IDC_PARAM4_VAL                  1110
#define IDC_PARAM1_TITLE                1111
#define IDC_PARAM2_TITLE                1112
#define IDC_PARAM3_TITLE                1113
#define IDC_PARAM4_TITLE                1114
#define IDC_PARAM1_NEDT                 1115
#define IDC_PARAM2_NEDT                 1116
#define IDC_PARAM3_NEDT                 1117
#define IDC_PARAM4_NEDT                 1118
#define IDC_PARAM5_TITLE                1119
#define IDC_BTN_SAVE_PARAMS             1120
#define IDC_PARAM6_TITLE                1121
#define IDC_PARAM7_TITLE                1122
#define IDC_PARAM8_TITLE                1123
#define IDC_PARAM9_TITLE                1124
#define IDC_PARAM5_NEDT                 1125
#define IDC_PARAM6_NEDT                 1126
#define IDC_PARAM7_NEDT                 1127
#define IDC_PARAM8_NEDT                 1128
#define IDC_PARAM6_VAL                  1129
#define IDC_PARAM7_BTN                  1130
#define IDC_PARAM7_VAL                  1131
#define IDC_PARAM8_BTN                  1132
#define IDC_PARAM8_VAL                  1133
#define IDC_PARAM9_NEDT                 1134
#define IDC_PARAM9_BTN                  1135
#define IDC_PARAM9_VAL                  1136
#define IDC_BTN_RESTORE_PARAMS          1137
#define IDC_NEDT_NPOINTS                1142
#define IDC_CMB_T_MEANING               1143
#define IDC_CMB_T_REFRESH               1144
#define IDC_RAD_MEANING1                1145
#define IDC_RAD_MEANING2                1146
#define IDC_RAD_MEANING3                1147
#define IDC_RAD_MEANING4                1148
#define IDC_CW_BTN_DEC_COEFF            1150
#define IDC_EDT_K_IMP_SEC               1151
#define IDC_CW_HISTO                    1152
#define IDC_EDT_N_BINS                  1153
#define IDC_CW_HISTO_1S                 1154
#define IDC_ALAN_CURVE                  1154
#define IDC_CW_HISTO_10S                1155
#define IDC_PRGRSS                      1155
#define IDC_CW_HISTO_100S               1156
#define IDC_BUTTON1                     1157
#define IDC_SOFTWARE_VERSION            1158
#define IDC_BTN_EXPORT                  1159
#define IDC_RAD_100M                    1160
#define IDC_THIS_SOFTWARE_VERSION       1160
#define IDC_RAD_1S                      1161
#define IDC_RAD_10S                     1162
#define IDC_RAD_100S                    1163
#define IDC_CHK_TSA                     1164
#define IDC_CHK_ROT_SPEED               1165
#define IDC_CHK_I1                      1166
#define IDC_CHK_I2                      1167
#define IDC_CHK_V_PP                    1168
#define IDC_CHK_AA                      1169
#define IDC_CHK_T1                      1170
#define IDC_CHK_T2                      1171
#define IDC_PRG_ACTION                  1172
#define IDC_BTN_BROWSE                  1173
#define IDC_LBL_OUTPUT_FILENAME         1174
#define IDC_PRGR                        1175
#define IDC_PRGR2                       1176
#define IDC_LBL_CURSOR_DX_VAL           1178
#define IDC_LBL_CURSOR_DY_VAL           1179
#define IDC_IC_RED_CURSOR               1180
#define IDC_LBL_CURSOR1_X_VAL           1181
#define IDC_LBL_CURSOR1_Y_VAL           1182
#define IDC_IC_BLUE_CURSOR              1183
#define IDC_LBL_CURSOR2_X_VAL           1184
#define IDC_LBL_CURSOR2_Y_VAL           1185
#define IDC_CURSOR_FRAME                1186
#define IDC_NO_MEANING                  1187
#define IDC_RAD_T1_TD1                  1189
#define IDC_RAD_T1_TD2                  1190
#define IDC_RAD_T1_TD3                  1191
#define IDC_RAD_T2_TD1                  1192
#define IDC_RAD_T2_TD2                  1193
#define IDC_RAD_T2_TD3                  1194
#define ID_START                        32771
#define ID_HISTOGRAM                    32772
#define ID_ALAN_CURVE                   32773
#define ID_ZOOMIN                       32775
#define ID_RESTORE_ZOOM                 32776
#define ID_SHOW_CURSORS                 32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1190
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
