#define ERROR_OK 0
#define ERROR_FLASH_LOAD_PARAMS_FAIL     1
#define ERROR_FLASH_SAVE_PARAMS_FAIL     2
#define ERROR_INITIAL_AMPL_ANG_TEST_FAIL 3
#define ERROR_NO_LASER_FIRING            4
#define ERROR_NO_TACT_SIGNAL             5
#define ERROR_TACT_SIGNAL_LOST           6